---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="centos" tag="7"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - function retry { counter=0 ; until "$@" ; do exit=$? ; counter=$(($counter + 1)) ; if [ $counter -ge 3 ] ; then return $exit ; fi ; done ; return 0; } ; retry tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack: "AW53ONXD+6/B9EOoLmqr/GjCWFCjK28Y5C6uNtZ7B9xMED+6G96j6wS78XLBQQcppul0/6REmLkWrSYN1tv8hhGtyUhKi6U35O4Fqn/umgNZfdYuc1uqiC5k+g4I7cWsrqTc3Bj5fgvGpOFEL3ZOwgINBQ7AHvISVEUxymoiR5jBWO0VqcEV4vIc2xHAQW/F9n5Aa9hiWnxs5MG9uYTDCPFmDeIZmfVQnWqeBGXQ+rIf9eOuGLjryAj56ak1qAiiuzqWxhX8VOVXQXyaNM/wB11GMKDXU+PB7A404p8zc0ZjWWabuqOo8Qf42vrGyqBTCpep+KhT+vZ3l8cVxt4pqHD0+eCVDvsyalCbpyHdz7H1fg94nSfJ3HWWCIpz7AaY5JCmq+SG71/vAqqozfcXatXfOKUXr0G7Y0KpqCa5yMWAEFUdSXCl+LnP7v1YcHOFsYuj11eC4rW1GAAQB7Ac5myYQO0eGRiCC5PGoYEYvvd3wOIMsoI8TaLyO5FfJoHRESeBT7oF4cA3i6sY+anZzxj1EQnxQLyvFHd7U0Bg44elj6nHxHJzs0SGJV5YXkDNWmOwMxjemFRQr4yCNQ/ljINAQU6yqMGsKud3k4QwIN66po05FujsTk93U2Il0myGXiuhBz3sDh7JNbNRROLjEbF/Uv3a0yAvCO33Tc/NgMI="
  email: false
