---
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="amazonlinux" tag="1"
    - image="amazonlinux"
    - image="centos" tag="7"
    - image="ubuntu"

matrix:
  allow_failures:

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "JLU2lW2nxLz9rgV/Azw+SJC7WOVCm9rP3BGVHCSD+SueuCAtmcEIWSeoIxSancXBfV323qA/ttywlk7DAD7ZQWfo2pWk9IiQ8ji2+zUV6YmvvmkK6wJtXClnbgFuFe7i6ylMRl1ROlw/1H7n8yo62tlTZWFCJUFBcNBtuK//jY5nh8jlFqSdLCtsw34h4uHlQK1x44B4R2bNU8NCxmrJUgsARt9bwvGAb/04Zd858hfLHpFVPUJVgpa2h6e+caDJLDgjyzJfot4JfGlk5WOwYQM1WIg6pyVJXiFQn/8hywYw9cT/uslStF7W8LHyhWFzUY26b8GYWjKDpeyx58DV02nI8/idvB3OceOOKMkba2cf8rQegQuevbS0rvw347u06CHcbdJaWSm2tfhHqFAMQXhbFyEuezUvHQClCgLCO+ZbKleDCoC49cqPXc+xXueeZAegCxMIxlIfwspWfkk9BNI9pUPyQSsuR6d2y/19t9HiLzoFrA5fheaRKCxJTjLE+RZsmk+jEl+ypyFGV0rJXI1qCwAa8uT2SiIntjadi2XKYxPVnm6v2ey7tM8fjI2HhBRHl7Bpq3A11uhfNbcW6r0z+9RshstGO1ERKRjaX7zO6czceQ1bL4oOppYtjcg58OxbZd8a1WUgKyfIwzS/2WuOTXiGqDwHHCu9qhmIpLM="
  email: false
