---
sudo: required
language: python
services: docker

env:
  - version=">=2.3,<2.4" distro="centos-7"
  - version=">=2.4,<2.5" distro="centos-7"
  - version=">=2.5,<2.6" distro="centos-7"
  - version=">=2.3,<2.4" distro="opensuse-42.3"
  - version=">=2.4,<2.5" distro="opensuse-42.3"
  - version=">=2.5,<2.6" distro="opensuse-42.3"
  - version=">=2.3,<2.4" distro="ubuntu-xenial"
  - version=">=2.4,<2.5" distro="ubuntu-xenial"
  - version=">=2.5,<2.6" distro="ubuntu-xenial"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install ansible"${version}"
  - pip install molecule
  - pip install docker-py

script:
  - molecule test --scenario-name "${distro}"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
