---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="centos" tag="7"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "sXYkpyHaqZyjQlync/w3sVo0NQGdgDsCuol03Y8HKvG8gBtN3inGG8+19PeX2sQfzHbHX2vzbKzCbHGpOJOK9UoVCBzymsQzX8eH34Sa6aX0SoOfgHxAsjLSj+YsZsDlXB7DOqlKsdggvYJs5r2Zxs0wF2+XXv9rzreyrhTWoy+A4Yv825phcPNDJLIWmJ11iHoKblDrX4vzOjiuaZT9S62r88CzDWK/nAt/qQ5fEXoi6Fe1P99fIAFr+zovuSVTaeO0spNmXHyF5zN3fA550Oc3FbHx5cwHuDTCqiXUoxjmnn4RkHhsWkTjaffb6bgsjzuQpsKmEtqejVSo9WHTsNjuW3yNsy9+ykJIhBZdArtPwZOUlQNrS2O89UwH4GV/rXK9nAlvyBIpHkB0zWBMwchW/EqtwfrldB+irqM4LIBtQwwf/IsnlNNIMVUci7PCcL8n/3sy8eCo174DChdNRvufDaL4qH50HZZdHTp83JDmj9XoNs2Zuv3Dx/sJlUwACRJmqYue//4SSJbIz4O4D1F6r6w3tKrYxTPJBdZ8TJeS7qbDnvGnd7LmV3bSwWyeN+MPt48AU643c43lA8pL1ojYpJ/8hatpoZSctlpJnF5tFCzUjmZBhl8q/jd8lYkDvLnM9BlMf1vP+YJTTaaguWvhK+HJa/0e2lonH6S4Myw="
  email: false
