---
sudo: required
language: python
services: docker

env:
  - version=">=2.6,<2.7" distro="alpine-latest" expectation="fail"
  - version="" distro="alpine-latest" expectation="fail"
  - version="devel" distro="alpine-latest" expectation="fail"
  - version=">=2.6,<2.7" distro="alpine-edge" expectation="fail"
  - version="" distro="alpine-edge" expectation="fail"
  - version="devel" distro="alpine-edge" expectation="fail"
  - version=">=2.6,<2.7" distro="archlinux" expectation="fail"
  - version="" distro="archlinux" expectation="fail"
  - version="devel" distro="archlinux" expectation="fail"
  - version=">=2.6,<2.7" distro="centos-6" expectation="fail"
  - version="" distro="centos-6" expectation="fail"
  - version="devel" distro="centos-6" expectation="fail"
  - version=">=2.6,<2.7" distro="centos-latest"
  - version="" distro="centos-latest"
  - version="devel" distro="centos-latest"
  - version=">=2.6,<2.7" distro="debian-latest" expectation="fail"
  - version="" distro="debian-latest" expectation="fail"
  - version="devel" distro="debian-latest" expectation="fail"
  - version=">=2.6,<2.7" distro="debian-stable" expectation="fail"
  - version="" distro="debian-stable" expectation="fail"
  - version="devel" distro="debian-stable" expectation="fail"
  - version=">=2.6,<2.7" distro="debian-unstable" expectation="fail"
  - version="" distro="debian-unstable" expectation="fail"
  - version="devel" distro="debian-unstable" expectation="fail"
  - version=">=2.6,<2.7" distro="fedora-latest" expectation="fail"
  - version="" distro="fedora-latest" expectation="fail"
  - version="devel" distro="fedora-latest" expectation="fail"
  - version=">=2.6,<2.7" distro="fedora-rawhide" expectation="fail"
  - version="" distro="fedora-rawhide" expectation="fail"
  - version="devel" distro="fedora-rawhide" expectation="fail"
  - version=">=2.6,<2.7" distro="opensuse-leap"
  - version="" distro="opensuse-leap"
  - version="devel" distro="opensuse-leap"
  - version=">=2.6,<2.7" distro="opensuse-tumbleweed" expectation="fail"
  - version="" distro="opensuse-tumbleweed" expectation="fail"
  - version="devel" distro="opensuse-tumbleweed" expectation="fail"
  - version=">=2.6,<2.7" distro="ubuntu-rolling"
  - version="" distro="ubuntu-rolling"
  - version="devel" distro="ubuntu-rolling"
  - version=">=2.6,<2.7" distro="ubuntu-latest" expectation="fail"
  - version="" distro="ubuntu-latest" expectation="fail"
  - version="devel" distro="ubuntu-latest" expectation="fail"
  - version=">=2.6,<2.7" distro="ubuntu-devel" expectation="fail"
  - version="" distro="ubuntu-devel" expectation="fail"
  - version="devel" distro="ubuntu-devel" expectation="fail"

matrix:
  allow_failures:
    - env: version=">=2.6,<2.7" distro="alpine-edge" expectation="fail"
    - env: version="" distro="alpine-edge" expectation="fail"
    - env: version="devel" distro="alpine-edge" expectation="fail"
    - env: version="devel" distro="alpine-latest" expectation="fail"
    - env: version="devel" distro="archlinux" expectation="fail"
    - env: version="devel" distro="centos-6" expectation="fail"
    - env: version="devel" distro="centos-latest"
    - env: version="devel" distro="debian-latest" expectation="fail"
    - env: version="devel" distro="debian-stable" expectation="fail"
    - env: version=">=2.6,<2.7" distro="debian-unstable" expectation="fail"
    - env: version="" distro="debian-unstable" expectation="fail"
    - env: version="devel" distro="debian-unstable" expectation="fail"
    - env: version="devel" distro="fedora-latest" expectation="fail"
    - env: version=">=2.6,<2.7" distro="fedora-rawhide" expectation="fail"
    - env: version="" distro="fedora-rawhide" expectation="fail"
    - env: version="devel" distro="fedora-rawhide" expectation="fail"
    - env: version="devel" distro="opensuse-leap"
    - env: version="devel" distro="opensuse-tumbleweed" expectation="fail"
    - env: version="devel" distro="ubuntu-rolling"
    - env: version=">=2.6,<2.7" distro="ubuntu-devel" expectation="fail"
    - env: version="" distro="ubuntu-devel" expectation="fail"
    - env: version="devel" distro="ubuntu-devel" expectation="fail"
    - env: version="devel" distro="ubuntu-latest" expectation="fail"

cache:
  - pip

install:
  - pip install --upgrade pip
  - if [ "${version}" != "devel" ] ; then pip install ansible"${version}" ; fi
  - if [ "${version}" = "devel" ] ; then pip install git+https://github.com/ansible/ansible.git@devel ; fi
  - pip install molecule
  - pip install docker

script:
  - if [ "${expectation}" = "fail" ] ; then ! molecule test --scenario-name "${distro}" ; else molecule test --scenario-name "${distro}" ; fi

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "G6UvyMX95KTyjt+cjnjCtK+r2/MAJ1sDWhFRzAyc2jQZHsV9cy310c12ebX1CYlHX4IOHfXLMHxos6nYEtQTEm30KQSmqp53bFCImgB6O4XP7/wnvrG0z27OABWuhq7UR6tRgAZ8yP89tk9qOwW2W2TpbGnJFVDTiVQhPci1zATCpoLjZqBToqe9oSWGvewpzW3JK2Yb2T1kIM+BFrwjg70kBKQQv7TAyJIsf6savGKCeEz/XSO1fzrvNW5oLmeMyNeYp4yVmSFjQ3f1+ncqkHpnZCFcpVetj6JqX9YKtG9lTVANCyC1BThB8uzsWdJGyMuCLDgu8ZUYW1numHFrwgmPXteeIh5vT6aBK274yJ5Z1D87gdG1FKOZNN7vYSUYveIrHOyzksLjYoSuoHs1aEenWeMQWsVrYEDMqRzVcuu6Rx5djvrE0XsQaSNEr/NcbciW+agkt3M98/g7O14YrO6C7nyXLxL4l8PAyxWFiJHzOcF+5eW6SRDA7yEMmiqZqo6WvckPSQMVrFtzB2wCIvYxmc/ixsWFZJ7kwGIF72/3/cSNgEXC04lmI4qwp8pUyq5kOoae+vSsz2qPnS23X0I8xWgwxzpoj04ygU4CL+FmoObyzkRSSwUHGOFm1+7DGdF95N3/pjzqlcGZj9WIdlCTEbs8wVf3BSPmfRi32ow="
  email: false
