---
# tasks file for mssql
- name: add yum repository packages-microsoft-com-mssql-server-2017
  yum_repository:
    name: "{{ item.name }}"
    baseurl: "{{ item.baseurl }}"
    description: "{{ item.description }}"
    gpgkey: "{{ mssql_gpgkey }}"
    gpgcheck: yes
  when:
    - ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux"
  with_items: "{{ mssql_rhel_repositories }}"
  tags:
    - preparation

- name: add zypper repository packages-microsoft-com-mssql-server-2017
  zypper_repository:
    name: "{{ item.name }}"
    repo: "{{ item.repo }}"
    auto_import_keys: yes
  when:
    - ansible_distribution == "openSUSE Leap"
  with_items: "{{ mssql_opensuse_repositories }}"
  tags:
    - preparation

- name: TEMPORARILY add apt-transport-https
  package:
    name: apt-transport-https
  when:
    - ansible_distribution == "Ubuntu"
  tags:
    - preparation

- name: add apt repository packages-microsoft-com-mssql-server-2017
  apt_repository:
    repo: deb [arch=amd64] "{{ item.repo }}" xenial main
  when:
    - ansible_distribution == "Ubuntu"
  with_items: "{{ mssql_ubuntu_repositories }}"
  tags:
    - preparation

- name: add apt key
  apt_key:
    url: "{{ mssql_gpgkey }}"
  when:
    - ansible_distribution == "Ubuntu"
  tags:
    - preparation

- name: install software in mssql_packages (package)
  package:
    name: "{{ item.name }}"
  with_items: "{{ mssql_packages }}"
  environment:
    ACCEPT_EULA: Y
  when:
    - ansible_distribution != "Ubuntu"
  tags:
    - installation

- name: install software in mssql_packages (apt)
  apt:
    name: "{{ item.name }}"
    allow_unauthenticated: yes
  with_items: "{{ mssql_packages }}"
  environment:
    ACCEPT_EULA: Y
  when:
    - ansible_distribution == "Ubuntu"
  notify:
    - configure mssql-server using mssql-conf
  tags:
    - installation

- name: flush handlers
  meta: flush_handlers

- name: start and enable mssql-server
  service:
    name: mssql-server
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != "docker"
  tags:
    - installation

- name: install pymssql
  pip:
    name: pymssql
  tags:
    - requirements
