---
# tasks file for mssql
- name: Add yum repository packages-microsoft-com-mssql-server-2017
  yum_repository:
    name: "{{ item.name }}"
    baseurl: "{{ item.baseurl }}"
    gpgkey: "{{ mssql_gpgkey }}"
    gpgcheck: yes
  when:
    - ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux"
  with_items: "{{ mssql_rhel_repositories }}"

- name: Add zypper repository packages-microsoft-com-mssql-server-2017
  zypper_repository:
    name: "{{ item.name }}"
    repo: "{{ item.repo }}"
    auto_import_keys: yes
  when:
    - ansible_distribution == "openSUSE Leap"
  with_items: "{{ mssql_opensuse_repositories }}"

- name: Add apt repository packages-microsoft-com-mssql-server-2017
  apt_repository:
    repo: deb [arch=amd64] "{{ item.repo }}" xenial main
  when:
    - ansible_distribution == "Ubuntu"
  with_items: "{{ mssql_ubuntu_repositories }}"
  notify:
    - add apt key

- name: flush handlers
  meta: flush_handlers

- name: install mssql-server
  package:
    name: mssql-server
    state: "{{ mssql_server }}"
  notify: configure mssql-server using mssql-conf

- name: flush handlers
  meta: flush_handlers

- name: start and enable mssql-server
  service:
    name: mssql-server
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != "docker"

- name: install mssql-tools
  package:
    name: "mssql-tools"
    state: "{{ mssql_tools }}"
  environment:
    ACCEPT_EULA: Y

- name: install pymssql
  pip:
    name: pymssql
