---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: rhel-7
    image: ami-c86c3f23
    instance_type: t2.medium
    vpc_subnet_id: subnet-0e688067
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  config_options:
    defaults:
      callback_plugins: /usr/lib/python2.7/site-packages/ara/plugins/callbacks
  inventory:
    host_vars:
      mssql-ubuntu-18.04:
        ansible_user: ubuntu
      mssql-centos-7:
        ansible_user: centos
      mssql-fedora-29:
        ansible_user: fedora
scenario:
  name: ec2
  create_sequence:
    - create
  check_sequence:
    - destroy
    - dependency
    - create
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - converge
  destroy_sequence:
    - destroy
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: goss
  lint:
    name: yamllint
