---
# handlers file for mssql
- name: restart mssql-server
  service:
    name: mssql-server
    state: restarted
  when:
    - ansible_virtualization_type != "docker"

- name: wait for tcp port
  wait_for:
    port: "{{ mssql_tcp_port }}"
