---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: mssql-centos-6
    image: centos:6
  - name: mssql-centos-7
    image: centos:7
  - name: phpmyadmin-debian-buster
    image: debian:buster
  - name: phpmyadmin-debian-jessie
    image: debian:jessie
  - name: phpmyadmin-debian-sid
    image: debian:sid
  - name: phpmyadmin-debian-stretch
    image: debian:stretch
  - name: phpmyadmin-fedora-23
    image: fedora:23
  - name: phpmyadmin-fedora-24
    image: fedora:24
  - name: phpmyadmin-fedora-25
    image: fedora:25
  - name: phpmyadmin-fedora-26
    image: fedora:26
  - name: phpmyadmin-fedora-27
    image: fedora:27
  - name: mssql-opensuse-42.3
    image: opensuse:42.3
  - name: mssql-ubuntu-xenial
    image: ubuntu:xenial
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - check
    - side_effect
    - verify
    - destroy
verifier:
  name: goss
  lint:
    name: 'None'
