---
- name: Converge
  hosts: all
  become: yes
  gather_facts: no
  strategy: free

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.buildtools
    - role: robertdebock.epel
    - role: robertdebock.scl
    - role: robertdebock.python-pip
    - role: ansible-role-mssql
